version: '3'
services:
  jnet:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./config.edn:/netrunner/config.edn
    ports:
      - 1042:1042
    depends_on:
      - mongodb
      - jnet_card_fetch
  jnet_card_fetch:
    build:
      context: ../
      dockerfile: docker/Dockerfile_fetch
    volumes:
      - ./config.edn:/netrunner/config.edn
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.8
    volumes:
      # former is local path to mongodb
      - mongodb_dir/:/data/db 
