version: '3'

services:
  jnet:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./config.edn:/netrunner/config.edn
      - /service_data/jnet_resources:/netrunner/resources
    networks:
      - db_network
      - web_network
    depends_on:
      - mongodb

  jnet_card_fetch:
    build:
      context: ../
      dockerfile: docker/Dockerfile_fetch
    volumes:
      - ./config.edn:/netrunner/config.edn
      - /root/netrunner-data/edn/:/netrunner/edn/
    networks:
      - db_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.6.8
    networks:
      - db_network
    volumes:
      - /user_data/jnet_mongodb_dir:/data/db 

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /service_data/jnet_resources:/netrunner/resources:/opt/jinteki/netrunner/resources
    networks:
      - web_network
    ports:
      - 80:80
    depends_on:
      - jnet

networks:
  db_network:
  web_network:
