version: '3'
services:
  jnet:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./config.edn:/netrunner/config.edn
      - /service_data/jnet_resources:/netrunner/resources
    ports:
      - 1042:1042
    depends_on:
      - mongodb
      - jnet_card_fetch
  jnet_card_fetch:
    build:
      context: ../
      dockerfile: docker/Dockerfile_fetch
    volumes:
      - ./config.edn:/netrunner/config.edn
      - /netrunner-data/edn/raw_data.edn:/netrunner/edn/raw_data.edn
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.8
    volumes:
      - /user_data/jnet_mongodb_dir:/data/db 
