version: '3'
services:
  jnet:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./config.edn:/netrunner/config.edn
    ports:
      - 1042:1042
    depends_on:
      - mongodb
      - jnet_card_fetch
    links:
      - mongodb
  jnet_card_fetch:
    build:
      context: ../
      dockerfile: docker/Dockerfile_fetch
    volumes:
      - ./config.edn:/netrunner/config.edn
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:3.6.8
